using System;
using System.Collections.Generic;
using System.Text;

namespace SignatureEmailParser.BusinessLogic.Helpers
{
    public class Countries
    {
        private static Dictionary<int, string> _countries = null;

        private Countries()
        {
        }

        private static Dictionary<int, string> GetCountries()
        {
            Dictionary<int, string> countries = new Dictionary<int, string>();
            countries.Add(0, "Unspecified");
            countries.Add(1, "Afghanistan");
            countries.Add(2, "Åland Islands");
            countries.Add(3, "Albania");
            countries.Add(4, "Algeria");
            countries.Add(5, "American Samoa");
            countries.Add(6, "Andorra");
            countries.Add(7, "Angola");
            countries.Add(8, "Anguilla");
            countries.Add(9, "Antarctica");
            countries.Add(10, "Antigua And Barbuda");
            countries.Add(11, "Argentina");
            countries.Add(12, "Armenia");
            countries.Add(13, "Aruba");
            countries.Add(14, "Australia");
            countries.Add(15, "Austria");
            countries.Add(16, "Azerbaijan");
            countries.Add(17, "Bahamas");
            countries.Add(18, "Bahrain");
            countries.Add(19, "Bangladesh");
            countries.Add(20, "Barbados");
            countries.Add(21, "Belarus");
            countries.Add(22, "Belgium");
            countries.Add(23, "Belize");
            countries.Add(24, "Benin");
            countries.Add(25, "Bermuda");
            countries.Add(26, "Bhutan");
            countries.Add(27, "Bolivia");
            countries.Add(28, "Bosnia And Herzegovina");
            countries.Add(29, "Botswana");
            countries.Add(30, "Bouvet Island");
            countries.Add(31, "Brazil");
            countries.Add(32, "British Indian Ocean Territory");
            countries.Add(33, "British Virgin Islands");
            countries.Add(34, "Brunei");
            countries.Add(35, "Bulgaria");
            countries.Add(36, "Burkina Faso");
            countries.Add(37, "Burundi");
            countries.Add(38, "Cambodia");
            countries.Add(39, "Cameroon");
            countries.Add(40, "Canada");
            countries.Add(41, "Cape Verde");
            countries.Add(42, "Caribbean Netherlands");
            countries.Add(43, "Cayman Islands");
            countries.Add(44, "Central African Republic");
            countries.Add(45, "Chad");
            countries.Add(46, "Chile");
            countries.Add(47, "China");
            countries.Add(48, "Christmas Island");
            countries.Add(49, "Cocos (keeling) Islands");
            countries.Add(50, "Colombia");
            countries.Add(51, "Comoros");
            countries.Add(52, "Cook Islands");
            countries.Add(53, "Costa Rica");
            countries.Add(54, "Côte D’ivoire");
            countries.Add(55, "Croatia");
            countries.Add(56, "Cuba");
            countries.Add(57, "Curaçao");
            countries.Add(58, "Cyprus");
            countries.Add(59, "Czechia");
            countries.Add(60, "Democratic Republic Of The Congo");
            countries.Add(61, "Denmark");
            countries.Add(62, "Djibouti");
            countries.Add(63, "Dominica");
            countries.Add(64, "Dominican Republic");
            countries.Add(65, "Ecuador");
            countries.Add(66, "Egypt");
            countries.Add(67, "El Salvador");
            countries.Add(68, "Equatorial Guinea");
            countries.Add(69, "Eritrea");
            countries.Add(70, "Estonia");
            countries.Add(71, "Ethiopia");
            countries.Add(72, "Falkland Islands");
            countries.Add(73, "Faroe Islands");
            countries.Add(74, "Fiji");
            countries.Add(75, "Finland");
            countries.Add(76, "France");
            countries.Add(77, "French Guiana");
            countries.Add(78, "French Polynesia");
            countries.Add(79, "French Southern Territories");
            countries.Add(80, "Gabon");
            countries.Add(81, "Gambia");
            countries.Add(82, "Georgia");
            countries.Add(83, "Germany");
            countries.Add(84, "Ghana");
            countries.Add(85, "Gibraltar");
            countries.Add(86, "Greece");
            countries.Add(87, "Greenland");
            countries.Add(88, "Grenada");
            countries.Add(89, "Guadeloupe");
            countries.Add(90, "Guam");
            countries.Add(91, "Guatemala");
            countries.Add(92, "Guernsey");
            countries.Add(93, "Guinea");
            countries.Add(94, "Guinea-bissau");
            countries.Add(95, "Guyana");
            countries.Add(96, "Haiti");
            countries.Add(97, "Heard Island And Mcdonald Islands");
            countries.Add(98, "Honduras");
            countries.Add(99, "Hong Kong");
            countries.Add(100, "Hungary");
            countries.Add(101, "Iceland");
            countries.Add(102, "India");
            countries.Add(103, "Indonesia");
            countries.Add(104, "Iran");
            countries.Add(105, "Iraq");
            countries.Add(106, "Ireland");
            countries.Add(107, "Isle Of Man");
            countries.Add(108, "Israel");
            countries.Add(109, "Italy");
            countries.Add(110, "Jamaica");
            countries.Add(111, "Japan");
            countries.Add(112, "Jersey");
            countries.Add(113, "Jordan");
            countries.Add(114, "Kazakhstan");
            countries.Add(115, "Kenya");
            countries.Add(116, "Kiribati");
            countries.Add(117, "Kosovo");
            countries.Add(118, "Kuwait");
            countries.Add(119, "Kyrgyzstan");
            countries.Add(120, "Laos");
            countries.Add(121, "Latvia");
            countries.Add(122, "Lebanon");
            countries.Add(123, "Lesotho");
            countries.Add(124, "Liberia");
            countries.Add(125, "Libya");
            countries.Add(126, "Liechtenstein");
            countries.Add(127, "Lithuania");
            countries.Add(128, "Luxembourg");
            countries.Add(129, "Macau");
            countries.Add(130, "Macedonia");
            countries.Add(131, "Madagascar");
            countries.Add(132, "Malawi");
            countries.Add(133, "Malaysia");
            countries.Add(134, "Maldives");
            countries.Add(135, "Mali");
            countries.Add(136, "Malta");
            countries.Add(137, "Marshall Islands");
            countries.Add(138, "Martinique");
            countries.Add(139, "Mauritania");
            countries.Add(140, "Mauritius");
            countries.Add(141, "Mayotte");
            countries.Add(142, "Mexico");
            countries.Add(143, "Micronesia");
            countries.Add(144, "Moldova");
            countries.Add(145, "Monaco");
            countries.Add(146, "Mongolia");
            countries.Add(147, "Montenegro");
            countries.Add(148, "Montserrat");
            countries.Add(149, "Morocco");
            countries.Add(150, "Mozambique");
            countries.Add(151, "Myanmar");
            countries.Add(152, "Namibia");
            countries.Add(153, "Nauru");
            countries.Add(154, "Nepal");
            countries.Add(155, "Netherlands");
            countries.Add(156, "Netherlands Antilles");
            countries.Add(157, "New Caledonia");
            countries.Add(158, "New Zealand");
            countries.Add(159, "Nicaragua");
            countries.Add(160, "Niger");
            countries.Add(161, "Nigeria");
            countries.Add(162, "Niue");
            countries.Add(163, "Norfolk Island");
            countries.Add(164, "North Korea");
            countries.Add(165, "Northern Mariana Islands");
            countries.Add(166, "Norway");
            countries.Add(167, "Oman");
            countries.Add(168, "Pakistan");
            countries.Add(169, "Palau");
            countries.Add(170, "Palestine");
            countries.Add(171, "Panama");
            countries.Add(172, "Papua New Guinea");
            countries.Add(173, "Paraguay");
            countries.Add(174, "Peru");
            countries.Add(175, "Philippines");
            countries.Add(176, "Pitcairn");
            countries.Add(177, "Poland");
            countries.Add(178, "Portugal");
            countries.Add(179, "Puerto Rico");
            countries.Add(180, "Qatar");
            countries.Add(181, "Republic Of The Congo");
            countries.Add(182, "Réunion");
            countries.Add(183, "Romania");
            countries.Add(184, "Russia");
            countries.Add(185, "Rwanda");
            countries.Add(186, "Saint Barthélemy");
            countries.Add(187, "Saint Helena");
            countries.Add(188, "Saint Kitts And Nevis");
            countries.Add(189, "Saint Lucia");
            countries.Add(190, "Saint Martin");
            countries.Add(191, "Saint Pierre And Miquelon");
            countries.Add(192, "Saint Vincent And The Grenadines");
            countries.Add(193, "Samoa");
            countries.Add(194, "San Marino");
            countries.Add(195, "São Tomé And Príncipe");
            countries.Add(196, "Saudi Arabia");
            countries.Add(197, "Senegal");
            countries.Add(198, "Serbia");
            countries.Add(199, "Seychelles");
            countries.Add(200, "Sierra Leone");
            countries.Add(201, "Singapore");
            countries.Add(202, "Sint Maarten");
            countries.Add(203, "Slovakia");
            countries.Add(204, "Slovenia");
            countries.Add(205, "Solomon Islands");
            countries.Add(206, "Somalia");
            countries.Add(207, "South Africa");
            countries.Add(208, "South Georgia And The South Sandwich Islands");
            countries.Add(209, "South Korea");
            countries.Add(210, "South Sudan");
            countries.Add(211, "Spain");
            countries.Add(212, "Sri Lanka");
            countries.Add(213, "Sudan");
            countries.Add(214, "Suriname");
            countries.Add(215, "Svalbard And Jan Mayen");
            countries.Add(216, "Swaziland");
            countries.Add(217, "Sweden");
            countries.Add(218, "Switzerland");
            countries.Add(219, "Syria");
            countries.Add(220, "Taiwan");
            countries.Add(221, "Tajikistan");
            countries.Add(222, "Tanzania");
            countries.Add(223, "Thailand");
            countries.Add(224, "Timor-leste");
            countries.Add(225, "Togo");
            countries.Add(226, "Tokelau");
            countries.Add(227, "Tonga");
            countries.Add(228, "Trinidad And Tobago");
            countries.Add(229, "Tunisia");
            countries.Add(230, "Turkey");
            countries.Add(231, "Turkmenistan");
            countries.Add(232, "Turks And Caicos Islands");
            countries.Add(233, "Tuvalu");
            countries.Add(234, "U.s. Virgin Islands");
            countries.Add(235, "Uganda");
            countries.Add(236, "Ukraine");
            countries.Add(237, "United Arab Emirates");
            countries.Add(238, "United Kingdom");
            countries.Add(239, "United States");
            countries.Add(240, "United States Minor Outlying Islands");
            countries.Add(241, "Uruguay");
            countries.Add(242, "Uzbekistan");
            countries.Add(243, "Vanuatu");
            countries.Add(244, "Vatican City");
            countries.Add(245, "Venezuela");
            countries.Add(246, "Vietnam");
            countries.Add(247, "Wallis And Futuna");
            countries.Add(248, "Western Sahara");
            countries.Add(249, "Yemen");
            countries.Add(250, "Zambia");
            countries.Add(251, "Zimbabwe");

            return countries;
        }

        public static Dictionary<int, string> GetInstance()
        {
            if (_countries == null)
            {
                _countries = GetCountries();
            }

            return _countries;
        }
    }
}
